### PR TITLE
Reworked dependencies and added development tutorial in the README.md

### PR DESCRIPTION
**Pull request by yrenum**
Removed unused binaries, deleted useless C# scripts and added glew licence

### CODE REVIEW

**Comment by yrenum** [comment]
Partially merged #1 in the last commit

**Comment by iAndyHD3** [comment]
But visual studio is not needed at all?

**Comment by yrenum** [comment]
Hi @iAndyHD3, to build the project VSCode is not a requirement, but maxnut uses VSCode to develop this mod, so I just added a tutorial to setup a development enviroment with it.

Also this PR contains a part of your #2, solving a possible merge conflict.

**Comment by iAndyHD3** [comment]
Yes that is fine, i also improved the readme in general but it can get changed later

**Pull request merged**
