### PR TITLE
Add build instructions to README

### LINKED ISSUE #183: Compiling code instractions
I was just hoping you could add some simple instructions on how to compile code in the read me just so people who are having problems with anti-virus can compile the code for themselves, thanks :)

### PR DESCRIPTION
**Pull request by Stronkkey**
scuffed
couldn't test it out (no windows) but its based on the build steps for the actions
Fixes: #183

### CODE REVIEW

**Comment by SpaghettDev** [comment]
These are wrong lol, well technically they'll work but no one uses the CLI to compile the project.
Usually you would use VSCode or MS VIsual Studio.

**Comment by maxnut** [comment]
i mean if somebody just wants to build the source i don't see anything particularly wrong

**Comment by Stronkkey** [comment]
Creating build instructions with gui would probably take another document so I don't think its worth it. Regardless, there isn't a reason you would build the project yourself unless you are adding new features.

**Comment by Stronkkey** [comment]
cool

**Comment by Stronkkey** [comment]
Seems to have been reverted in the Geode branch?

**Pull request merged**
